server:
  port: 8081
  servlet:
    context-path: /api/
logging:
  file:
    name: another-server.log
  logback:
    rollingpolicy:
      file-name-pattern: another-server-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
      max-history: 5
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/another-authorization
openfga:
  api-url: http://localhost:8080
  store-id: 01JSBTQABT9ZMY9R151H2J6FWR
  authorization-model-id: 01JSBTQCFJDPTNTFWBQCC9XEK0
